// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4iyYbe2aGm2PKEEehBhLfK0wQSxVPqdI',
    appId: '1:78340777097:web:b2a460aea19ac77f425258',
    messagingSenderId: '78340777097',
    projectId: 'dev0208',
    authDomain: 'dev0208.firebaseapp.com',
    storageBucket: 'dev0208.appspot.com',
    measurementId: 'G-Z3WJ3V1K3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtej5jJC4aEWRkoz5xmehE4ORUxcJgWcQ',
    appId: '1:78340777097:android:3399cb5c3f7743e6425258',
    messagingSenderId: '78340777097',
    projectId: 'dev0208',
    storageBucket: 'dev0208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmSf_woAtM8uSTBoEfHnqLFkYdGK7NEnI',
    appId: '1:78340777097:ios:cc4c0f97c99ad8e7425258',
    messagingSenderId: '78340777097',
    projectId: 'dev0208',
    storageBucket: 'dev0208.appspot.com',
    androidClientId:
        '78340777097-ua733sn118sm6s8v8ddnvf2q42e64lm1.apps.googleusercontent.com',
    iosClientId:
        '78340777097-33l547og6dtcelm2j31557tdmk215mq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.neeww',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmSf_woAtM8uSTBoEfHnqLFkYdGK7NEnI',
    appId: '1:78340777097:ios:cc4c0f97c99ad8e7425258',
    messagingSenderId: '78340777097',
    projectId: 'dev0208',
    storageBucket: 'dev0208.appspot.com',
    androidClientId:
        '78340777097-ua733sn118sm6s8v8ddnvf2q42e64lm1.apps.googleusercontent.com',
    iosClientId:
        '78340777097-33l547og6dtcelm2j31557tdmk215mq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.neeww',
  );
}
